-- 1. id_system table
CREATE TABLE IF NOT EXISTS ID_SYSTEM (
    ID SERIAL PRIMARY KEY,
    TIMESTAMP TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    FULL_NAME VARCHAR(255) NOT NULL,
    DOB DATE NOT NULL,
    LIBRARY_NAME VARCHAR(255) NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    USER_ID VARCHAR(50) UNIQUE NOT NULL,
    CITY VARCHAR(255),
    COUNTRY VARCHAR(255),
    ZIPCODE VARCHAR(20),
    LIBRARY_ID INTEGER,
    FOREIGN KEY (LIBRARY_ID) REFERENCES PUBLIC.LIBRARIES_LIBRARY(ID)
);

-- 2. student_registration_data table
CREATE TABLE IF NOT EXISTS STUDENT_REGISTRATION_DATA (
    ID SERIAL PRIMARY KEY,
    TIMESTAMP TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    USER_ID VARCHAR(50) UNIQUE NOT NULL,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    FULL_NAME VARCHAR(255) NOT NULL,
    LIBRARY_NAME VARCHAR(255) NOT NULL,
    GENDER VARCHAR(10) NOT NULL,
    DATE_OF_BIRTH DATE NOT NULL,
    GRADE VARCHAR(50) NOT NULL,
    NUMBER_OF_FAMILY_MEMBERS VARCHAR(10) NOT NULL,
    FAMILY_STATUS VARCHAR(255) NOT NULL,
    NUMBER_OF_INCOME_EARNING_FAMILY VARCHAR(10) NOT NULL,
    EDUCATIONAL_OBSTACLES TEXT NOT NULL,
    FAMILY_SUPPORT_LEVEL INTEGER NOT NULL,
    FAVORITE_SCHOOL_SUBJECT VARCHAR(255) NOT NULL,
    SUBJECT_MOST_USEFUL_FOR_FUTURE_CAREER VARCHAR(255) NOT NULL,
    MOST_CHALLENGING_SCHOOL_SUBJECT VARCHAR(255) NOT NULL,
    HOW_HEAR_LIBRARY TEXT NOT NULL,
    TRAVEL_TIME_TO_LIBRARY VARCHAR(255) NOT NULL,
    ADDITIONAL_LIBRARY_RESOURCES_WANTED TEXT NOT NULL,
    LIBRARY_USE_GOALS TEXT NOT NULL,
    LIBRARY_USAGE_CHALLENGES TEXT,
    LIBRARY_ID INTEGER,
    FOREIGN KEY (LIBRARY_ID) REFERENCES PUBLIC.LIBRARIES_LIBRARY(ID),
    FOREIGN KEY (USER_ID) REFERENCES ID_SYSTEM(USER_ID)
);

-- 3. non_student_registration_data table
CREATE TABLE IF NOT EXISTS NON_STUDENT_REGISTRATION_DATA (
    ID SERIAL PRIMARY KEY,
    USER_ID VARCHAR(50) UNIQUE NOT NULL,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    FULL_NAME VARCHAR(255) NOT NULL,
    LIBRARY_NAME VARCHAR(255) NOT NULL,
    GENDER VARCHAR(10) NOT NULL,
    DATE_OF_BIRTH DATE NOT NULL,
    PHONE_NUMBER VARCHAR(20) NOT NULL,
    EMAIL_ADDRESS VARCHAR(255),
    HOME_ADDRESS VARCHAR(255),
    HOW_HEARD_ABOUT_LIBRARY VARCHAR(255),
    TRAVEL_TIME_TO_LIBRARY VARCHAR(255),
    ADDITIONAL_LIBRARY_RESOURCES_WANTED TEXT,
    LIBRARY_ID INTEGER,
    FOREIGN KEY (LIBRARY_ID) REFERENCES PUBLIC.LIBRARIES_LIBRARY(ID),
    FOREIGN KEY (USER_ID) REFERENCES ID_SYSTEM(USER_ID)
);

-- 4. sign_in_records table
CREATE TABLE IF NOT EXISTS SIGN_IN_RECORDS (
    ID SERIAL PRIMARY KEY,
    USER_ID VARCHAR(50) UNIQUE,
    LIBRARY_NAME VARCHAR(255) NOT NULL,
    FULL_NAME VARCHAR(255) NOT NULL,
    GENDER VARCHAR(50) NOT NULL,
    DOB DATE NOT NULL,
    SIGN_IN_TIMESTAMP TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    LIBRARY_ID INTEGER,
    FOREIGN KEY (LIBRARY_ID) REFERENCES PUBLIC.LIBRARIES_LIBRARY(ID),
    FOREIGN KEY (USER_ID) REFERENCES ID_SYSTEM(USER_ID)
);

-- 5. libraries_library table
CREATE TABLE IF NOT EXISTS LIBRARIES_LIBRARY (
    ID SERIAL PRIMARY KEY,
    IS_ACCEPTING_NEW_MENTORS BOOLEAN NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    LIBRARY_CODE VARCHAR(255) UNIQUE,
    ADDRESS_1 VARCHAR(255),
    ADDRESS_2 VARCHAR(255),
    CITY VARCHAR(255),
    COUNTRY VARCHAR(255),
    NOTES VARCHAR(255),
    POBOXNUMBER VARCHAR(255),
    POSTAL_CODE VARCHAR(255),
    STATE_PROVINCE VARCHAR(255),
    STATUS INTEGER NOT NULL,
    UNIQUEID UUID NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);